# AP25: resource baselines and a long-run soak, measured from OUTSIDE.
#
# Everything here polls the camera over HTTP - /api/v1/telemetry and /metrics
# are both native Machino routes, so a sample costs the daemon one small
# response and forks nothing. That is deliberate: an earlier per-second sampler
# that forked on the camera was suspected of being part of a fault, and an
# instrument that might cause what it measures is not an instrument.
#
# Load is generated by real /ws/video consumers, the same WebSocket client
# tools/mse-drift.ps1 uses. Phases run in sequence with a COLD_IDLE settle
# between them, so a leak shows up as a floor that keeps rising rather than as
# a number that happens to be big while streaming.
#
#   pwsh tools/soak.ps1 -Cam 192.168.1.10 -Pw '...' -PhaseSec 300 -Cycles 3
#
# -Hours runs the long soak instead: the same phases repeated with periodic
# connect/disconnect, for that many hours.

param(
    [string]$Cam       = '192.168.1.10',
    [string]$Pw        = '',
    [int]$PhaseSec     = 180,       # how long each load phase is held
    [int]$SettleSec    = 30,        # COLD_IDLE settle between phases (grace is 5 s)
    [int]$SampleSec    = 15,        # telemetry poll interval
    [int]$Cycles       = 2,         # COLD_IDLE -> ACTIVE -> COLD_IDLE repetitions
    [double]$Hours     = 0,         # >0 turns this into the long soak
    [string]$Out       = ''
)

$ErrorActionPreference = 'Stop'
if (-not $Out) { $Out = Join-Path $env:TEMP "soak-$(Get-Date -Format yyyyMMdd-HHmmss).txt" }
function Note($s) {
    $line = "$(Get-Date -Format 'HH:mm:ss')  $s"
    [Console]::WriteLine($line); Add-Content -Path $Out -Value $line -Encoding utf8
}

function Get-Cookie {
    param([string]$cam, [string]$pw)
    $c = New-Object Net.Sockets.TcpClient; $c.Connect($cam, 80); $s = $c.GetStream()
    $b = "username=root&password=$pw"
    $by = [Text.Encoding]::ASCII.GetBytes("POST /login HTTP/1.1`r`nHost: $cam`r`nContent-Type: application/x-www-form-urlencoded`r`nContent-Length: $($b.Length)`r`nConnection: close`r`n`r`n$b")
    $s.Write($by, 0, $by.Length); $s.Flush(); Start-Sleep -Milliseconds 400
    $buf = New-Object byte[] 8192; $n = $s.Read($buf, 0, $buf.Length)
    $h = [Text.Encoding]::ASCII.GetString($buf, 0, $n); $c.Close()
    if ($h -match 'Set-Cookie:\s*([^;\r\n]+)') { return $Matches[1] }
    return ''
}

function Fetch {
    param([string]$cam, [string]$path, [string]$ck)
    $c = New-Object Net.Sockets.TcpClient
    try {
        $c.Connect($cam, 80); $s = $c.GetStream(); $s.ReadTimeout = 15000
        $by = [Text.Encoding]::ASCII.GetBytes("GET $path HTTP/1.1`r`nHost: $cam`r`nCookie: $ck`r`nConnection: close`r`n`r`n")
        $s.Write($by, 0, $by.Length); $s.Flush()
        $ms = New-Object IO.MemoryStream; $bb = New-Object byte[] 65536
        try { while ($true) { $k = $s.Read($bb, 0, $bb.Length); if ($k -le 0) { break }; $ms.Write($bb, 0, $k) } } catch {}
        $txt = [Text.Encoding]::UTF8.GetString($ms.ToArray())
        $i1 = $txt.IndexOf("`r`n`r`n"); $i2 = $txt.IndexOf("`n`n")
        $cut = if ($i1 -ge 0 -and ($i2 -lt 0 -or $i1 -lt $i2)) { $i1 + 4 } elseif ($i2 -ge 0) { $i2 + 2 } else { 0 }
        return $txt.Substring($cut)
    } catch { return '' } finally { try { $c.Close() } catch {} }
}

# One row of everything worth watching. MemAvailable comes from /metrics
# (node-exporter names, which Machino serves natively), the rest from
# /api/v1/telemetry.
function Sample {
    param([string]$cam, [string]$ck, [string]$phase)
    $t = Fetch -cam $cam -path '/api/v1/telemetry' -ck $ck
    $m = Fetch -cam $cam -path '/metrics' -ck $ck
    $j = $null; try { $j = $t | ConvertFrom-Json } catch {}
    if (-not $j) { return $null }
    $avail = 0
    if ($m -match 'node_memory_MemAvailable_bytes\s+([0-9.e+]+)') { $avail = [double]$Matches[1] / 1024 }
    $load = 0
    if ($m -match 'node_load1\s+([0-9.]+)') { $load = [double]$Matches[1] }
    return [pscustomobject]@{
        t        = Get-Date
        phase    = $phase
        life     = $j.lifecycle
        gen      = $j.pipeline_generation
        rss      = [int]$j.process.rss_kb
        cpu      = [math]::Round([double]$j.process.cpu_percent, 1)
        threads  = [int]$j.process.threads
        availkb  = [int]$avail
        load1    = $load
        rtsp     = [int]$j.sessions.rtsp_sessions
        rtc      = [int]$j.sessions.webrtc_sessions
        wsv      = [int]$j.sessions.ws_video_clients
        wsl      = [int]$j.sessions.ws_logs_clients
        senderr  = [int]$j.sessions.webrtc_send_errors
        initfail = [int]$j.sessions.init_failures
        initretry= [int]$j.sessions.init_retries
        dropped  = [int]$j.media.dropped_frames
        fps      = [math]::Round([double]$j.media.encoded_fps, 2)
    }
}

# A /ws/video consumer that just drains. MemoryStream, never a per-byte list:
# a slow reader makes the camera drop frames for it and then the measurement is
# of the instrument.
$consumer = {
    param($cam, $stream, $ck, $seconds)
    $ws = New-Object System.Net.WebSockets.ClientWebSocket
    if ($ck) { $ws.Options.SetRequestHeader("Cookie", $ck) }
    $cts = New-Object System.Threading.CancellationTokenSource
    try { $ws.ConnectAsync([Uri]("ws://$cam/ws/video?stream=$stream"), $cts.Token).Wait(15000) | Out-Null } catch { return "connect failed" }
    if ($ws.State -ne 'Open') { return "not open" }
    $seg = New-Object 'System.ArraySegment[byte]' (, (New-Object byte[] 262144))
    $sw = [Diagnostics.Stopwatch]::StartNew(); $bytes = 0; $msgs = 0
    while ($sw.Elapsed.TotalSeconds -lt $seconds -and $ws.State -eq 'Open') {
        $t = $ws.ReceiveAsync($seg, $cts.Token)
        if (-not $t.Wait(20000)) { break }
        $r = $t.Result
        if ($r.MessageType -eq 'Close') { break }
        $bytes += $r.Count; if ($r.EndOfMessage) { $msgs++ }
    }
    try { $ws.Abort() } catch {}
    return "stream=$stream msgs=$msgs bytes=$bytes"
}

$rows = New-Object Collections.Generic.List[object]
function Hold {
    param([string]$phase, [int]$seconds, [int[]]$streams)
    $jobs = @()
    foreach ($s in $streams) { $jobs += Start-Job -ScriptBlock $consumer -ArgumentList $Cam, $s, $ck, ($seconds + 10); Start-Sleep -Milliseconds 300 }
    $deadline = (Get-Date).AddSeconds($seconds)
    while ((Get-Date) -lt $deadline) {
        Start-Sleep -Seconds $SampleSec
        $r = Sample -cam $Cam -ck $ck -phase $phase
        if ($r) { $rows.Add($r) | Out-Null }
    }
    foreach ($j in $jobs) { Stop-Job $j -ErrorAction SilentlyContinue; Remove-Job $j -Force -ErrorAction SilentlyContinue }
    $last = $rows | Where-Object { $_.phase -eq $phase } | Select-Object -Last 1
    if ($last) { Note ([string]::Format([Globalization.CultureInfo]::InvariantCulture,
        "  {0,-16} rss={1,5} kB  avail={2,6} kB  cpu={3,5}  thr={4}  wsv={5}  fps={6}  dropped={7}",
        $phase, $last.rss, $last.availkb, $last.cpu, $last.threads, $last.wsv, $last.fps, $last.dropped)) }
}

function Settle {
    param([string]$phase)
    Start-Sleep -Seconds $SettleSec
    $r = Sample -cam $Cam -ck $ck -phase $phase
    if ($r) {
        $rows.Add($r) | Out-Null
        Note ([string]::Format([Globalization.CultureInfo]::InvariantCulture,
            "  {0,-16} rss={1,5} kB  avail={2,6} kB  life={3}  gen={4}  wsv={5}  initfail={6} initretry={7}",
            $phase, $r.rss, $r.availkb, $r.life, $r.gen, $r.wsv, $r.initfail, $r.initretry))
    }
}

Note "soak  cam=$Cam phase=${PhaseSec}s settle=${SettleSec}s sample=${SampleSec}s cycles=$Cycles hours=$Hours"
$ck = if ($Pw) { Get-Cookie -cam $Cam -pw $Pw } else { '' }
Note "session: $(if ($ck) { 'obtained' } else { 'none' })"

$reps = if ($Hours -gt 0) { [int]([math]::Ceiling($Hours * 3600 / [math]::Max(1, ($PhaseSec * 3 + $SettleSec * 4)))) } else { $Cycles }
Note "running $reps cycle(s)"

for ($i = 1; $i -le $reps; $i++) {
    Note "--- cycle $i/$reps ---"
    Settle "COLD_IDLE[$i]"
    Hold "MSE_MAIN[$i]"     $PhaseSec @(0)
    Settle "COLD_IDLE[$i]b"
    Hold "MSE_MAIN_SUB[$i]" $PhaseSec @(0, 1)
    Settle "COLD_IDLE[$i]c"
    Hold "MSE_3CLIENT[$i]"  $PhaseSec @(0, 0, 0)
    Settle "COLD_IDLE[$i]d"
}

Note ''
Note 'phase             n   rss_min  rss_max  avail_min  cpu_max  thr  dropped  initfail  initretry'
Note ('-' * 100)
foreach ($p in ($rows | Select-Object -ExpandProperty phase -Unique)) {
    $g = $rows | Where-Object { $_.phase -eq $p }
    Note ([string]::Format([Globalization.CultureInfo]::InvariantCulture,
        "{0,-16} {1,3}  {2,7}  {3,7}  {4,9}  {5,7}  {6,3}  {7,7}  {8,8}  {9,9}",
        $p, @($g).Count,
        ($g | Measure-Object rss -Minimum).Minimum, ($g | Measure-Object rss -Maximum).Maximum,
        ($g | Measure-Object availkb -Minimum).Minimum, ($g | Measure-Object cpu -Maximum).Maximum,
        ($g | Measure-Object threads -Maximum).Maximum, ($g | Measure-Object dropped -Maximum).Maximum,
        ($g | Measure-Object initfail -Maximum).Maximum, ($g | Measure-Object initretry -Maximum).Maximum))
}

# The acceptance question, asked of the COLD_IDLE floors only: a leak shows as
# a floor that keeps rising across cycles, not as a number that is big while
# three clients are streaming.
$cold = $rows | Where-Object { $_.phase -like 'COLD_IDLE*' }
if ($cold.Count -ge 2) {
    $first = ($cold | Select-Object -First 1).rss
    $last  = ($cold | Select-Object -Last 1).rss
    Note ''
    Note "COLD_IDLE rss floor: first $first kB -> last $last kB  (delta $($last - $first) kB over $($cold.Count) settles)"
    Note "gauges at the end: wsv=$(($rows | Select-Object -Last 1).wsv) rtsp=$(($rows | Select-Object -Last 1).rtsp) rtc=$(($rows | Select-Object -Last 1).rtc)"
}
Note "report: $Out"
