#include "core/net/hostapd_conf.hpp"

#include "core/net/proc_net.hpp"

#include <cstdio>

namespace machino { namespace net {

namespace {

// Same octet parsing the API validator uses, kept local so this file has no
// dependency on the API layer. A malformed address here is a udhcpd that
// refuses to start, which is invisible until a client fails to get a lease.
bool dotted_quad(const std::string& s, uint32_t& out)
{
    unsigned a = 0, b = 0, c = 0, d = 0;
    int consumed = 0;
    if (std::sscanf(s.c_str(), "%u.%u.%u.%u%n", &a, &b, &c, &d, &consumed) != 4) return false;
    if (consumed != (int)s.size()) return false;
    if (a > 255 || b > 255 || c > 255 || d > 255) return false;
    out = (a << 24) | (b << 16) | (c << 8) | d;
    return true;
}

} // namespace

bool hostapd_value_is_safe(const std::string& v)
{
    for (unsigned char ch : v)
        if (ch < 0x20 || ch == 0x7f) return false;
    return true;
}

bool hostapd_band_for_channel(int channel, std::string& hw_mode_out)
{
    if (channel == 0) { hw_mode_out = "g"; return true; }   // auto, 2.4 GHz
    if (channel >= 1 && channel <= 14)  { hw_mode_out = "g"; return true; }
    if (channel >= 36 && channel <= 196) { hw_mode_out = "a"; return true; }
    return false;
}

bool hostapd_conf_from(const WifiApConfig& cfg, const std::string& ifname,
                       const std::string& driver, std::string& out, std::string& err)
{
    if (ifname.empty() || !hostapd_value_is_safe(ifname)) { err = "the interface name is not usable"; return false; }
    if (driver.empty() || !hostapd_value_is_safe(driver)) { err = "the hostapd driver name is not usable"; return false; }

    if (cfg.ssid.empty())      { err = "an access point needs an ssid"; return false; }
    if (cfg.ssid.size() > 32)  { err = "an ssid is at most 32 bytes"; return false; }
    if (!hostapd_value_is_safe(cfg.ssid)) {
        // hostapd.conf has no escaping at all: a newline here would append
        // directives of the caller's choosing, and "wpa=0" among them turns a
        // secured access point into an open one.
        err = "the ssid contains a character that cannot be written to hostapd.conf";
        return false;
    }

    std::string hw_mode;
    if (!hostapd_band_for_channel(cfg.channel, hw_mode)) {
        err = "channel " + std::to_string(cfg.channel) + " is not a 2.4 GHz or 5 GHz channel";
        return false;
    }

    const bool open = (cfg.security == WifiSecurity::Open);
    if (!open) {
        if (!hostapd_value_is_safe(cfg.passphrase)) {
            err = "the passphrase contains a character that cannot be written to hostapd.conf";
            return false;
        }
        // hostapd refuses to start outside this range rather than falling
        // back, and a camera whose access point never came up is the worst
        // outcome: it is the recovery path.
        if (cfg.passphrase.size() < 8 || cfg.passphrase.size() > 63) {
            err = "a WPA passphrase is 8 to 63 characters";
            return false;
        }
    }
    if (cfg.security == WifiSecurity::Wep) {
        err = "WEP is not offered: it is broken, and hostapd has dropped it";
        return false;
    }
    if (cfg.security == WifiSecurity::Wpa) {
        err = "WPA1 is not offered for an access point we create; use wpa2";
        return false;
    }

    std::string s;
    s += "# generated by machino -- edits are overwritten when the AP is reconfigured\n";
    s += "interface=" + ifname + "\n";
    s += "driver=" + driver + "\n";
    s += "ssid=" + cfg.ssid + "\n";
    s += "hw_mode=" + hw_mode + "\n";
    s += "channel=" + std::to_string(cfg.channel) + "\n";
    // The control interface is how machino reconfigures the AP without ever
    // starting a process: hostapd runs from boot, and DISABLE/ENABLE over this
    // socket does the rest. Forking while IMP is live is the documented
    // trigger of an out-of-memory incident on this camera.
    s += "ctrl_interface=/var/run/hostapd\n";
    s += "ignore_broadcast_ssid=0\n";

    if (open) {
        s += "auth_algs=1\n";
        s += "wpa=0\n";
    } else {
        s += "auth_algs=1\n";         // open system only; shared key is WEP-era
        s += "wpa=2\n";               // WPA2 and WPA3 both ride RSN
        s += "wpa_passphrase=" + cfg.passphrase + "\n";
        s += "wpa_pairwise=CCMP\n";
        s += "rsn_pairwise=CCMP\n";
        if (cfg.security == WifiSecurity::Wpa3) {
            s += "wpa_key_mgmt=SAE\n";
            s += "ieee80211w=2\n";           // SAE requires management frame protection
        } else if (cfg.security == WifiSecurity::Wpa2Wpa3) {
            s += "wpa_key_mgmt=WPA-PSK SAE\n";
            s += "ieee80211w=1\n";           // optional, so WPA2-only clients still join
        } else {
            s += "wpa_key_mgmt=WPA-PSK\n";
        }
    }

    out = s;
    return true;
}

bool udhcpd_conf_from(const WifiApConfig& cfg, const std::string& ifname,
                      std::string& out, std::string& err)
{
    if (ifname.empty() || !hostapd_value_is_safe(ifname)) { err = "the interface name is not usable"; return false; }

    uint32_t ip = 0, lo = 0, hi = 0;
    if (!dotted_quad(cfg.ipv4, ip))       { err = "the access point address is not an IPv4 address"; return false; }
    if (!dotted_quad(cfg.dhcp_start, lo)) { err = "dhcpStart is not an IPv4 address"; return false; }
    if (!dotted_quad(cfg.dhcp_end, hi))   { err = "dhcpEnd is not an IPv4 address"; return false; }

    if (lo > hi) { err = "the DHCP pool starts after it ends"; return false; }
    if (ip >= lo && ip <= hi) {
        // udhcpd will happily hand out the router's own address and then the
        // whole segment stops working, in a way that looks like a driver bug.
        err = "the access point's own address is inside the DHCP pool";
        return false;
    }

    // A /24 is what the defaults describe and what the pool checks assume;
    // anything else needs a netmask field the API does not offer yet.
    if ((ip & 0xffffff00u) != (lo & 0xffffff00u) || (ip & 0xffffff00u) != (hi & 0xffffff00u)) {
        err = "the DHCP pool is not on the same /24 as the access point";
        return false;
    }

    std::string s;
    s += "# generated by machino -- edits are overwritten when the AP is reconfigured\n";
    s += "interface " + ifname + "\n";
    s += "start " + cfg.dhcp_start + "\n";
    s += "end " + cfg.dhcp_end + "\n";
    s += "option subnet " + prefix_to_netmask(24) + "\n";
    s += "option router " + cfg.ipv4 + "\n";
    // The camera is the DNS the clients get. It is not a resolver, so this is
    // only right when the AP is also the route out; when it is not, a client
    // that cannot resolve is the expected and correct outcome rather than a
    // silent redirect somewhere else.
    s += "option dns " + cfg.ipv4 + "\n";
    s += "option lease 3600\n";
    s += "lease_file /var/run/udhcpd.leases\n";
    s += "pidfile /var/run/udhcpd.pid\n";

    out = s;
    return true;
}

}} // namespace machino::net
