// /proc and resolv.conf parsing, against text captured from the camera.
//
// The byte order in /proc/net/route is the trap worth a test: the columns are
// the host-order value of a network-order address, so a naive read prints the
// gateway with its octets reversed and everything still looks like an IP.
#include "core/net/proc_net.hpp"
#include <cstdio>
#include <string>

using namespace machino;
using namespace machino::net;

extern int g_fail_ext, g_pass_ext;
#define TCHECK(cond) do { if (cond) { ++g_pass_ext; } else { ++g_fail_ext; fprintf(stderr, "FAIL %s:%d: %s\n", __FILE__, __LINE__, #cond); } } while (0)

namespace {

// From the T40NN: eth0 up, default via 192.168.1.1.
const char* kRoute =
    "Iface\tDestination\tGateway \tFlags\tRefCnt\tUse\tMetric\tMask\t\tMTU\tWindow\tIRTT\n"
    "eth0\t00000000\t0101A8C0\t0003\t0\t0\t0\t00000000\t0\t0\t0\n"
    "eth0\t0001A8C0\t00000000\t0001\t0\t0\t0\t00FFFFFF\t0\t0\t0\n";

void test_default_route_octet_order()
{
    DefaultRoute r;
    TCHECK(best_default_route(kRoute, r));
    // 0101A8C0 little-endian -> C0 A8 01 01 -> 192.168.1.1. Read the other way
    // round it would be 1.1.168.192, which also looks like an address.
    TCHECK(r.gateway == "192.168.1.1");
    TCHECK(r.ifname == "eth0");
    TCHECK(r.metric == 0);
}

void test_only_the_default_route_counts()
{
    // The second line is the on-link /24, not a default route.
    TCHECK(parse_proc_net_route(kRoute).size() == 1);
}

void test_no_default_route_is_reported_as_none()
{
    const char* only_onlink =
        "Iface\tDestination\tGateway \tFlags\tRefCnt\tUse\tMetric\tMask\n"
        "eth0\t0001A8C0\t00000000\t0001\t0\t0\t0\t00FFFFFF\n";
    DefaultRoute r;
    TCHECK(!best_default_route(only_onlink, r));
    TCHECK(!best_default_route("", r));
    TCHECK(!best_default_route("Iface\tDestination\n", r));
}

void test_two_default_routes_and_the_metric_decides()
{
    // Ethernet and LTE both up is the whole point of the failover work, so
    // this is a normal state, not a corner case.
    const char* both =
        "Iface\tDestination\tGateway \tFlags\tRefCnt\tUse\tMetric\tMask\n"
        "wwan0\t00000000\t0100000A\t0003\t0\t0\t200\t00000000\n"
        "eth0\t00000000\t0101A8C0\t0003\t0\t0\t10\t00000000\n";
    TCHECK(parse_proc_net_route(both).size() == 2);
    DefaultRoute r;
    TCHECK(best_default_route(both, r));
    TCHECK(r.ifname == "eth0" && r.metric == 10);
}

void test_a_link_local_default_route_has_no_gateway()
{
    // A point-to-point modem link commonly has none, and reporting "0.0.0.0"
    // would put a fake address on the status page.
    const char* ppp =
        "Iface\tDestination\tGateway \tFlags\tRefCnt\tUse\tMetric\tMask\n"
        "wwan0\t00000000\t00000000\t0001\t0\t0\t0\t00000000\n";
    DefaultRoute r;
    TCHECK(best_default_route(ppp, r));
    TCHECK(r.gateway.empty() && r.ifname == "wwan0");
}

void test_short_and_garbage_lines_are_dropped_not_half_read()
{
    const char* junk =
        "Iface\tDestination\n"
        "eth0\t00000000\n"
        "eth0\tZZZZZZZZ\t0101A8C0\t0003\t0\t0\t0\t00000000\n"
        "eth0\t00000000\t0101A8C0\t0003\t0\t0\tnope\t00000000\n";
    TCHECK(parse_proc_net_route(junk).empty());
}

void test_resolv_conf()
{
    const char* rc =
        "# generated by udhcpc\n"
        "nameserver 192.168.1.1\n"
        "; a comment\n"
        "search lan\n"
        "nameserver 8.8.8.8\n"
        "nameserver\n";                  // no value: not a nameserver
    const std::vector<std::string> ns = parse_resolv_conf(rc);
    TCHECK(ns.size() == 2);
    TCHECK(ns.size() == 2 && ns[0] == "192.168.1.1" && ns[1] == "8.8.8.8");
    TCHECK(parse_resolv_conf("").empty());
}

void test_proc_net_dev_counters()
{
    const char* dev =
        "Inter-|   Receive                                                |  Transmit\n"
        " face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed\n"
        "    lo:   12345      10    0    0    0     0          0         0    12345      10    0    0    0     0       0          0\n"
        "  eth0: 99887766  120000    0    1    0     0          0         3  55443322   90000    0    0    0     0       0          0\n";
    uint64_t rx = 0, tx = 0;
    TCHECK(parse_proc_net_dev(dev, "eth0", rx, tx));
    TCHECK(rx == 99887766ull && tx == 55443322ull);
    // An absent interface is not the same answer as one sitting at zero.
    TCHECK(!parse_proc_net_dev(dev, "wlan0", rx, tx));
}

void test_proc_net_dev_with_the_counter_jammed_against_the_name()
{
    // Busybox-era kernels do not pad, and "wwan0:12345678" is what you get.
    const char* dev =
        "Inter-|   Receive |  Transmit\n"
        " face |bytes\n"
        "wwan0:12345678 100 0 0 0 0 0 0 87654321 90 0 0 0 0 0 0\n";
    uint64_t rx = 0, tx = 0;
    TCHECK(parse_proc_net_dev(dev, "wwan0", rx, tx));
    TCHECK(rx == 12345678ull && tx == 87654321ull);
}

void test_netmask_conversions()
{
    TCHECK(netmask_to_prefix("255.255.255.0") == 24);
    TCHECK(netmask_to_prefix("255.255.255.255") == 32);
    TCHECK(netmask_to_prefix("0.0.0.0") == 0);
    TCHECK(netmask_to_prefix("24") == 24);
    TCHECK(netmask_to_prefix("0") == 0);

    // A non-contiguous mask is not a netmask, and the kernel will not take it
    // either -- accepting it here would push the failure into ifconfig.
    TCHECK(netmask_to_prefix("255.255.0.255") == -1);
    TCHECK(netmask_to_prefix("255.0.255.0") == -1);
    TCHECK(netmask_to_prefix("") == -1);
    TCHECK(netmask_to_prefix("33") == -1);
    TCHECK(netmask_to_prefix("255.255.255") == -1);
    TCHECK(netmask_to_prefix("255.255.255.0 ") == -1);
    TCHECK(netmask_to_prefix("256.0.0.0") == -1);

    TCHECK(prefix_to_netmask(24) == "255.255.255.0");
    TCHECK(prefix_to_netmask(0) == "0.0.0.0");
    TCHECK(prefix_to_netmask(32) == "255.255.255.255");
    TCHECK(prefix_to_netmask(33).empty());
    TCHECK(prefix_to_netmask(-1).empty());

    for (int p = 0; p <= 32; ++p) TCHECK(netmask_to_prefix(prefix_to_netmask(p)) == p);
}

} // namespace

void run_proc_net_tests()
{
    test_default_route_octet_order();
    test_only_the_default_route_counts();
    test_no_default_route_is_reported_as_none();
    test_two_default_routes_and_the_metric_decides();
    test_a_link_local_default_route_has_no_gateway();
    test_short_and_garbage_lines_are_dropped_not_half_read();
    test_resolv_conf();
    test_proc_net_dev_counters();
    test_proc_net_dev_with_the_counter_jammed_against_the_name();
    test_netmask_conversions();
}
